[[BiCePS]]
arch = "aarch64"
git-tree-sha1 = "4b278e7f69847a33552200abc42e5639f554ff8c"
os = "macos"

    [[BiCePS.download]]
    sha256 = "b2f260f406206337c91f6c3ad66e00c543c6150fcf072065764992f68a1589de"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.aarch64-apple-darwin.tar.gz"
[[BiCePS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a994b67c971e9fc312aaeb4de08300dd0fc1503f"
libc = "glibc"
os = "linux"

    [[BiCePS.download]]
    sha256 = "25edd2ee4d303f43c627ec619e48c989768a202994fd12888d40d55432e8b77b"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.aarch64-linux-gnu-cxx03.tar.gz"
[[BiCePS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13f3354f4698854d10f2f7c8acbd50a4d8dee15b"
libc = "glibc"
os = "linux"

    [[BiCePS.download]]
    sha256 = "a6689f8ccd00e8142356fd48645a255ca01a6124b573126d004652306020dd28"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.aarch64-linux-gnu-cxx11.tar.gz"
[[BiCePS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74a1bee167f02919c262f59366c1ce7ffcc41df3"
libc = "musl"
os = "linux"

    [[BiCePS.download]]
    sha256 = "c70148e7e63442e9b1fbf03800fa3c2edd4f1f245a5c8b55a8c30835cc62fe2c"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.aarch64-linux-musl-cxx03.tar.gz"
[[BiCePS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c7ab227f3ef792c51fefe9aabbf4ce235997db9"
libc = "musl"
os = "linux"

    [[BiCePS.download]]
    sha256 = "029c88edf0dfd3a7a8bc7961c43dc803338860523afd539bc1e55ddac840743c"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.aarch64-linux-musl-cxx11.tar.gz"
[[BiCePS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7cc32077c64f6eba815485603839c72fcd9b1e2c"
libc = "glibc"
os = "linux"

    [[BiCePS.download]]
    sha256 = "018848cd03bb632671cfda233d0b88639043cb9f0f23e6c40d8b62c2116d927c"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[BiCePS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8259970db0000f1c2ac17f3a372508ffa40f84b"
libc = "glibc"
os = "linux"

    [[BiCePS.download]]
    sha256 = "4f70f4e3c6c48075efa5ff717e74bb4f65a3efaf1f672d4f7ea3acd6aa59d69d"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[BiCePS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2596a59ec76f1cead4e83c271092892793cb61d7"
libc = "musl"
os = "linux"

    [[BiCePS.download]]
    sha256 = "e21d54dcecaee544ac93b6e947365130e4a62d324e507a2eaf75ad68e04c89c7"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.armv6l-linux-musleabihf-cxx03.tar.gz"
[[BiCePS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d4f4de85712ec76ee4b21f3866ac7f3f79e366d"
libc = "musl"
os = "linux"

    [[BiCePS.download]]
    sha256 = "7e1766b4498f230e856f07e521fd5dab9807d1dbadbb53cf6e0ad42235785335"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.armv6l-linux-musleabihf-cxx11.tar.gz"
[[BiCePS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "602f3a3f1877c181b9377d66610ff571c614481f"
libc = "glibc"
os = "linux"

    [[BiCePS.download]]
    sha256 = "14696cd0fc5a6b1d3b84d3cb3709914850fbaced4a1235dc78089be1621ff867"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[BiCePS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0fbc10b7609ed436562c366d372ae2edbc4c1b1f"
libc = "glibc"
os = "linux"

    [[BiCePS.download]]
    sha256 = "fe39dd6964214de48d5c91c3eee28b8a60f987c7e9f6ad8db7c621dbaeadb785"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[BiCePS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "52efee99738e368e15e9f87abc84594fdf31ecb1"
libc = "musl"
os = "linux"

    [[BiCePS.download]]
    sha256 = "d898e67ef7955d7ee7ed48e59ed6ffb58ed7eea617dc99e32e582a3c280186c0"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.armv7l-linux-musleabihf-cxx03.tar.gz"
[[BiCePS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e768304c22cc1e23395fd907dabf30c35840f849"
libc = "musl"
os = "linux"

    [[BiCePS.download]]
    sha256 = "5705382cf048e719cb7381f53daeb56fc2b52386b33fa0dde030fd032855385d"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.armv7l-linux-musleabihf-cxx11.tar.gz"
[[BiCePS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "30b354eeeab3cb2252566a1e32fdc134ab19f773"
libc = "glibc"
os = "linux"

    [[BiCePS.download]]
    sha256 = "6a13bf699541c6bb27c3801fa704d84c58c5a2708e985f151672c5cc3c3840c1"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.i686-linux-gnu-cxx03.tar.gz"
[[BiCePS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5eb7dbdfd1a2a8a5153b1eb0b9451c1f4f6e3a09"
libc = "glibc"
os = "linux"

    [[BiCePS.download]]
    sha256 = "812f386bc25e82b3bfff68b8aebad1550dc3eadff975f8465705b8a5b903fcf6"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.i686-linux-gnu-cxx11.tar.gz"
[[BiCePS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba946bb07b1503c175552479a92c56c64d2819af"
libc = "musl"
os = "linux"

    [[BiCePS.download]]
    sha256 = "304685fc5613ca59b5a0f870b803905209403d87af10a33259ada2f448c0aeee"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.i686-linux-musl-cxx03.tar.gz"
[[BiCePS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "962a6105ea14cc315763be19abe34d7c573bdfb4"
libc = "musl"
os = "linux"

    [[BiCePS.download]]
    sha256 = "bc1f22b20a9a89709becef059d70b144989cb71ee5924aa2919b05675a112665"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.i686-linux-musl-cxx11.tar.gz"
[[BiCePS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be478a41cdd35e1e28edbf39d74b7b710c8d0941"
os = "windows"

    [[BiCePS.download]]
    sha256 = "557c0601d273490f1f5e6d3982ec49bec1566d108f1d988f460be78ff42fd1c6"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.i686-w64-mingw32-cxx03.tar.gz"
[[BiCePS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "446da99c763f5d46121f65270ca061c2a2a6718c"
os = "windows"

    [[BiCePS.download]]
    sha256 = "60507b8e6c8c888099e3e4478986014c70155aaf8bf0ac22afe18233af81efd4"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.i686-w64-mingw32-cxx11.tar.gz"
[[BiCePS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8470ab76eb5b4353db0921e4299aa61f16de000c"
libc = "glibc"
os = "linux"

    [[BiCePS.download]]
    sha256 = "d1d20c43d3e06af59dd425887732317450c458c5242a876eda1df8b1354ef24d"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.powerpc64le-linux-gnu-cxx03.tar.gz"
[[BiCePS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e421ffd8eb0788a62b7162f0af2de0154d325ec8"
libc = "glibc"
os = "linux"

    [[BiCePS.download]]
    sha256 = "98adb9363d652ac810e9e7b89b437d12ba7dd7f56669223857a7466fc79d3346"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.powerpc64le-linux-gnu-cxx11.tar.gz"
[[BiCePS]]
arch = "x86_64"
git-tree-sha1 = "6fdb7731a1b17b00cf8b47acf21f04a501e5cd21"
os = "macos"

    [[BiCePS.download]]
    sha256 = "9a5aacd45c3b7601b2c6da3f580c1dd446a4ad4dec435d5f69f01f10bc9d4528"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.x86_64-apple-darwin.tar.gz"
[[BiCePS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "999a18698a5e6bae30b80b02a28549066edef9aa"
libc = "glibc"
os = "linux"

    [[BiCePS.download]]
    sha256 = "12d6b144f612b83c185c6c051033ebaa7917ce97030edfc0fcb11f17b490af64"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.x86_64-linux-gnu-cxx03.tar.gz"
[[BiCePS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3450b67f0523802e08cffb98762c26c4e67e08fc"
libc = "glibc"
os = "linux"

    [[BiCePS.download]]
    sha256 = "9445b9b86013c7d16e8ed5ac3b25bb9afffc00c4932db0c4c8583c91580f630c"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.x86_64-linux-gnu-cxx11.tar.gz"
[[BiCePS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96323f9f201ba2816d72c70feadcbcc0cef1feb1"
libc = "musl"
os = "linux"

    [[BiCePS.download]]
    sha256 = "9733b88eb185629670f4325ce34d462ba73c5ffc44967df48bbb941cf0e7c008"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.x86_64-linux-musl-cxx03.tar.gz"
[[BiCePS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "917ffcb21d2f8c6fd52a39e537d3090c3f667f75"
libc = "musl"
os = "linux"

    [[BiCePS.download]]
    sha256 = "e4f44970675de04f5e6d434eb0327e665b9b6b129e6187cf370b9ccf8a445be1"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.x86_64-linux-musl-cxx11.tar.gz"
[[BiCePS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ff66f3e50865430c057ba8aeed371ff06092c55"
os = "windows"

    [[BiCePS.download]]
    sha256 = "4c65f71b110a60ca8d9d405b45a37880c9c1a1d6f9a44cbe7b7ebcb697d5bf1f"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.x86_64-w64-mingw32-cxx03.tar.gz"
[[BiCePS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73727ab0d3710d0ff1027c7f68c8113d147996c7"
os = "windows"

    [[BiCePS.download]]
    sha256 = "8a711bc7eb2d6bc167104410d3618f77fde77ebae3cd10dd912338f02c2d6ae3"
    url = "https://github.com/JuliaBinaryWrappers/BiCePS_jll.jl/releases/download/BiCePS-v0.9400.400+0/BiCePS.v0.9400.400.x86_64-w64-mingw32-cxx11.tar.gz"
